// SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause
/* Copyright (c) 2020 Facebook */
/* Adapted by yanniszark in 2024 */

// syscount is a BPF program that counts the number of times each syscall is
// called. It uses a BPF map of type BPF_MAP_TYPE_PERCPU_HASH to store the
// counts. The map is per-cpu so that we don't need to use a lock. The
// userspace program simply aggregates the counts from all the CPUs.


// vmlinux.h is the only file you will need to get kernel definitions!
// It is generated by bpftool and contains all the kernel definitions.
#include "vmlinux.h"
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "Dual BSD/GPL";


// Map of type hash (essentially a key-value store)
// Key: syscall number
// Value: number of times the syscall was called
struct {
	__uint(type, BPF_MAP_TYPE_PERCPU_HASH);
	__type(key, u64);
	__type(value, u64);
	__uint(max_entries, 500);  // most linux systems have 300-400 syscalls
} syscall_id_to_count SEC(".maps");


SEC("tracepoint/syscount")
int syscount(struct trace_event_raw_sys_enter *ctx) {
	// Interpret ctx
	u64 syscall_id = ctx->id;
	u64 *value;
	// Get the value from the map and increment
	value = bpf_map_lookup_elem(&syscall_id_to_count, &syscall_id);
	if (value) {
		bpf_printk("Syscall %d called %d times\n", syscall_id, *value);
		*value += 1;
	} else {
		u64 zero = 0;
		bpf_printk("Syscall %d called for the first time\n", syscall_id);
		bpf_map_update_elem(&syscall_id_to_count, &syscall_id, &zero, BPF_ANY);
	}
    return 0;
}
