// SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause
/* Copyright (c) 2020 Facebook */
/* Adapted by yanniszark in 2024 */

// xdp.bpf.c is a simple BPF firewall program.

// vmlinux.h is the only file you will need to get kernel definitions!
// It is generated by bpftool and contains all the kernel definitions.
#include "vmlinux.h"

#include <bpf/bpf_endian.h>
#include <bpf/bpf_helpers.h>

char LICENSE[] SEC("license") = "Dual BSD/GPL";

SEC("xdp")
int xdp_firewall(struct xdp_md *ctx) {
    // We see the raw ethernet frame here.
    // To filter on higher-level protocols, we need to parse it.
    void *data = (void *)(long)ctx->data;
    void *data_end = (void *)(long)ctx->data_end;

    // Parse IP
    struct iphdr *ip = data + sizeof(struct ethhdr);
    // Verifier check.
    if ((void *)(ip + 1) > data_end) return XDP_PASS;
    if (ip->protocol != IPPROTO_UDP) {
        return XDP_PASS;
    }

    // Parse UDP
    struct udphdr *udp =
        (struct udphdr *)(data + sizeof(struct ethhdr) + sizeof(struct iphdr));
    // Verifier check.
    if ((void *)(udp + 1) > data_end) return XDP_PASS;

    // Block 11111
    if (udp->dest == bpf_htons(11111)) {
        bpf_printk("Dropping packet to port 11111\n");
        return XDP_DROP;
    }
    return XDP_PASS;
}
